# Uncomment the following line to enable deep sleep
# CONFIG_ZMK_SLEEP=y

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y

# Configuration for custom screen
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

## Animation preferences

# This shield uses a fixed range for the chart and gauge deflection.
# If you set this option to n, it will switch to a dynamic range, like the default nice!view shield,
# which dynamically adjusts based on the last 10 WPM values provided by ZMK.
#CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE=y

# You can adjust the maximum value of the fixed range to align with your current goal (in this case 100wpm).
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE_MAX=100

# If you find the animation distracting (or want to save on battery usage), you can turn it off by setting this option to n.
# It will instead pick a random frame of the animation every time you restart your keyboard.
CONFIG_NICE_VIEW_GEM_ANIMATION=n

# Alternatively, you can slow down the animation. A high value, such as 96000, slows the animation considerably,
# showing the next frame every couple of seconds.
# The animation consists of 16 frames, and the default value of 960 milliseconds plays it at 60 fps.
#CONFIG_NICE_VIEW_GEM_ANIMATION_MS=960